language: python
python:
  - "3.6"

install:
  - pip install pylint
  - pip install sphinx sphinx-rtd-theme m2r
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pylint fusion_report/
  - pytest
