language: python
python:
  - "3.6"

install:
  - pip install flake8 mypy
  - pip install -r requirements.txt
  - python setup.py install

script:
  - flake8 fusion_report/
  - mypy fusion_report/

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/
    on:
      branch: master
      python: 3.6