language: python
python:
  - "3.6"
cache: pip

jobs:
  include:
    - stage: lint
      script:
        - pip install -r requirements-dev.txt
        - flake8 fusion_report/
        - mypy fusion_report/
    - stage: running-test
      before_script:
        - pip install -r requirements.txt
        - python setup.py install
      script:
        - fusion_report --help
        - fusion_report run --help
        - fusion_report download --help
    - stage: publish-documentation
      if: type = push AND branch = master
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/
        keep_history: true

stages:
  - lint
  - running-test
  - publish-documentation
